
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'ra_dw_ecommerce'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'ra_dw_ecommerce'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  ra_dw_ecommerce:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: view
    staging:
      stg_shopify_ecommerce:
        +materialized: table
        +schema: staging
      stg_ga4_events:
        +materialized: table
        +schema: staging
    integration:
      +materialized: table
      +schema: integration
    warehouse:
      +materialized: table
      +schema: ecommerce # This will create analytics_ecommerce dataset
      wh_dim_date:
        +alias: dim_date
      wh_dim_customers:
        +alias: dim_customers
      wh_dim_products:
        +alias: dim_products
      wh_dim_categories:
        +alias: dim_categories
      wh_dim_customer_metrics:
        +alias: dim_customer_metrics
      wh_fact_orders:
        +alias: fact_orders
      wh_fact_ga4_sessions:
        +alias: fact_sessions
      wh_fact_customer_journey:
        +alias: fact_customer_journey
      wh_fact_events:
        +alias: fact_events
      wh_fact_inventory:
        +alias: fact_inventory
      wh_dim_channels_enhanced:
        +alias: dim_channels
  shopify:
    +schema: raw # leave blank for just the target_schema
  shopify_source:
    +schema: raw # leave blank for just the target_schema


seeds:
  ra_dw_ecommerce:
    shopify:
      +schema: fivetran_shopify_demo
    ga4:
      +schema: fivetran_ga4_demo
      events_sample:
        +column_types:
          event_date: STRING
          event_timestamp: INTEGER
          event_name: STRING
          event_previous_timestamp: INTEGER
          event_value_in_usd: FLOAT64
          event_bundle_sequence_id: INTEGER
          event_server_timestamp_offset: INTEGER
          user_id: STRING
          user_pseudo_id: STRING
          privacy_info: STRING
          user_properties: STRING
          user_first_touch_timestamp: INTEGER
          user_ltv: STRING
          device: STRING
          geo: STRING
          app_info: STRING
          traffic_source: STRING
          stream_id: STRING
          platform: STRING
          event_params: STRING
          items: STRING
          ecommerce: STRING
    google_ads:
      +schema: google_ads
    facebook_ads:
      +schema: facebook_ads
      facebook_account_history:
        +alias: account_history
      facebook_campaign_history:
        +alias: campaign_history
      facebook_ad_set_history:
        +alias: ad_set_history
      facebook_ad_history:
        +alias: ad_history
      facebook_creative_history:
        +alias: creative_history
      facebook_basic_ad:
        +alias: basic_ad
      facebook_basic_ad_actions:
        +alias: basic_ad_actions
      facebook_basic_ad_action_values:
        +alias: basic_ad_action_values
    pinterest_ads:
      +schema: pinterest_ads
      pinterest_advertiser_history:
        +alias: advertiser_history
      pinterest_campaign_history:
        +alias: campaign_history
      pinterest_ad_group_history:
        +alias: ad_group_history
      pinterest_pin_promotion_history:
        +alias: pin_promotion_history
      pinterest_ad_group_report:
        +alias: ad_group_report
      pinterest_pin_promotion_report:
        +alias: pin_promotion_report
    instagram_business:
      +schema: instagram_business
    klaviyo:
      +schema: klaviyo

vars:
    shopify_using_fulfillment_event: false # false by default. 
    shopify_using_metafield: false  #true by default.
    shopify_using_discount_code_app: false #false by default.
    shopify_using_product_variant_media: false #false by default.
    shopify_using_abandoned_checkout: false # true by default. Setting to false will disable `abandoned_checkout`, `abandoned_checkout_discount_code`, and `abandoned_checkout_shipping_line`.
    shopify_database: ra-development
    shopify_schema: analytics_ecommerce_fivetran_shopify_demo
    
    # Google Ads configuration
    google_ads_database: ra-development
    google_ads_schema: analytics_ecommerce_google_ads
    google_auto_tagging_enabled: true
    
    # Facebook Ads configuration
    facebook_ads_database: ra-development
    facebook_ads_schema: analytics_ecommerce_facebook_ads
    
    # Instagram Business configuration
    instagram_business_database: ra-development
    instagram_business_schema: analytics_ecommerce_instagram_business
    instagram_business_user_history_identifier: user_history
    instagram_business_media_history_identifier: media_history
    instagram_business_media_insights_identifier: media_insights
    
    # Pinterest Ads configuration
    pinterest_ads_database: ra-development
    pinterest_ads_schema: analytics_ecommerce_pinterest_ads
    pinterest_schema: analytics_ecommerce_pinterest_ads
    pinterest_database: ra-development
    
    # Pinterest table identifiers (pointing to our aliased tables)
    pinterest_ads_advertiser_history_identifier: advertiser_history
    pinterest_ads_campaign_history_identifier: campaign_history
    pinterest_ads_ad_group_history_identifier: ad_group_history
    pinterest_ads_pin_promotion_history_identifier: pin_promotion_history
    pinterest_ads_ad_group_report_identifier: ad_group_report
    pinterest_ads_pin_promotion_report_identifier: pin_promotion_report
    # Tables we don't have - use non-existent names to keep them empty
    pinterest_ads_advertiser_report_identifier: advertiser_report_missing
    pinterest_ads_campaign_report_identifier: campaign_report_missing
    pinterest_ads_keyword_history_identifier: keyword_history_missing
    pinterest_ads_keyword_report_identifier: keyword_report_missing
    pinterest_ads_pin_promotion_targeting_report_identifier: pin_promotion_targeting_report_missing
    pinterest_ads_targeting_geo_identifier: targeting_geo_missing
    pinterest_ads_targeting_geo_region_identifier: targeting_geo_region_missing
    
    # Ad Reporting configuration - enable only the platforms we have
    ad_reporting__google_ads_enabled: true
    ad_reporting__facebook_ads_enabled: true
    ad_reporting__amazon_ads_enabled: false
    ad_reporting__apple_search_ads_enabled: false
    ad_reporting__linkedin_ads_enabled: false
    ad_reporting__microsoft_ads_enabled: false
    ad_reporting__pinterest_ads_enabled: true
    ad_reporting__reddit_ads_enabled: false
    ad_reporting__snapchat_ads_enabled: false
    ad_reporting__tiktok_ads_enabled: false
    ad_reporting__twitter_ads_enabled: false
    
    # Klaviyo configuration
    klaviyo_database: ra-development
    klaviyo_schema: analytics_ecommerce_klaviyo
    klaviyo__email_attribution_lookback: 120
    klaviyo__sms_attribution_lookback: 24
    klaviyo__count_metrics: ['Received Email', 'Opened Email', 'Clicked Email', 'Marked Email as Spam', 'Unsubscribed', 'Placed Order', 'Ordered Product', 'Viewed Product', 'Started Checkout', 'Active on Site']
    klaviyo__sum_revenue_metrics: ['Placed Order', 'Ordered Product']