version: 2

models:
  - name: wh_dim_date
    description: "Date dimension table with comprehensive calendar attributes"
    columns:
      - name: date_key
        description: "Surrogate key for date dimension (YYYYMMDD format)"
        tests:
          - unique
          - not_null
      - name: date_actual
        description: "Actual date value"
        tests:
          - unique
          - not_null
      - name: year_number
        description: "Calendar year"
        tests:
          - not_null
      - name: quarter_number
        description: "Calendar quarter (1-4)"
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4]
      - name: month_number
        description: "Calendar month (1-12)"
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
      - name: day_of_week_number
        description: "Day of week number (1=Sunday, 7=Saturday)"
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6, 7]

  - name: wh_dim_customers
    description: "Customer dimension with surrogate keys and comprehensive customer attributes"
    columns:
      - name: customer_key
        description: "Surrogate key for customer dimension"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Natural key from Shopify"
        tests:
          - unique
          - not_null
      - name: customer_email
        description: "Customer email address"
        tests:
          - not_null
      - name: customer_segment
        description: "Customer segmentation based on purchase behavior"
        tests:
          - accepted_values:
              values: ['High Value', 'Repeat Customer', 'One-time Customer', 'No Orders']
      - name: customer_value_tier
        description: "Customer value tier based on lifetime value"
        tests:
          - accepted_values:
              values: ['VIP', 'High Value', 'Medium Value', 'Low Value', 'Minimal Value']
      - name: is_current
        description: "SCD Type 2 flag indicating current record"
        tests:
          - not_null
          - accepted_values:
              values: [true, false]

  - name: wh_dim_products
    description: "Product dimension with surrogate keys and comprehensive product attributes"
    columns:
      - name: product_key
        description: "Surrogate key for product dimension"
        tests:
          - unique
          - not_null
      - name: product_id
        description: "Natural key from Shopify"
        tests:
          - unique
          - not_null
      - name: product_title
        description: "Product title"
        tests:
          - not_null
      - name: product_performance_category
        description: "Product performance based on sales"
        tests:
          - accepted_values:
              values: ['Best Seller', 'Popular', 'Moderate', 'Low Selling', 'No Sales']
      - name: revenue_tier
        description: "Revenue tier classification"
        tests:
          - accepted_values:
              values: ['Top Revenue Generator', 'High Revenue', 'Medium Revenue', 'Low Revenue', 'No Revenue']
      - name: is_current
        description: "SCD Type 2 flag indicating current record"
        tests:
          - not_null
          - accepted_values:
              values: [true, false]

  - name: wh_fact_orders
    description: "Order fact table with dimensional foreign keys and comprehensive order metrics"
    columns:
      - name: order_key
        description: "Surrogate key for order fact"
        tests:
          - unique
          - not_null
      - name: customer_key
        description: "Foreign key to customer dimension"
        tests:
          - not_null
          - relationships:
              to: ref('wh_dim_customers')
              field: customer_key
      - name: order_date_key
        description: "Foreign key to date dimension for order date"
        tests:
          - not_null
          - relationships:
              to: ref('wh_dim_date')
              field: date_key
      - name: order_id
        description: "Natural key from Shopify"
        tests:
          - unique
          - not_null
      - name: order_total_price
        description: "Total order amount"
        tests:
          - not_null
      - name: net_order_value
        description: "Net order value after refunds"
        tests:
          - not_null

  - name: wh_fact_ga4_sessions
    description: "Website session fact table with comprehensive session and engagement metrics"
    columns:
      - name: session_key
        description: "Surrogate key for session fact"
        tests:
          - unique
          - not_null
      - name: session_date_key
        description: "Foreign key to date dimension for session date"
        tests:
          - not_null
          - relationships:
              to: ref('wh_dim_date')
              field: date_key
      - name: session_id
        description: "Natural key for website session"
        tests:
          - unique
          - not_null
      - name: user_pseudo_id
        description: "User pseudo ID from website analytics"
        tests:
          - not_null
      - name: session_type
        description: "Session classification based on user behavior"
        tests:
          - accepted_values:
              values: ['Converting', 'Checkout Started', 'Added to Cart', 'Product Browsing', 'General Browsing']

  - name: wh_fact_customer_journey
    description: "Customer journey fact table linking website sessions to ecommerce conversions"
    columns:
      - name: journey_key
        description: "Surrogate key for customer journey fact"
        tests:
          - unique
          - not_null
      - name: customer_key
        description: "Foreign key to customer dimension"
        tests:
          - not_null
          - relationships:
              to: ref('wh_dim_customers')
              field: customer_key
      - name: order_key
        description: "Foreign key to order fact"
        tests:
          - not_null
          - relationships:
              to: ref('wh_fact_orders')
              field: order_key
      - name: session_key
        description: "Foreign key to GA4 session fact"
        tests:
          - not_null
          - relationships:
              to: ref('wh_fact_ga4_sessions')
              field: session_key
      - name: journey_complexity
        description: "Classification of customer journey complexity"
        tests:
          - accepted_values:
              values: ['Single Session', 'Short Journey', 'Medium Journey', 'Long Journey']
      - name: conversion_timeline
        description: "Timeline from first touch to conversion"
        tests:
          - accepted_values:
              values: ['Same Day', 'Within 3 Days', 'Within 1 Week', 'Within 1 Month', 'Long Consideration']

tests:
  - name: test_dim_customer_scd_type2_integrity
    description: "Ensures SCD Type 2 integrity for customer dimension"
    sql: |
      select customer_id
      from {{ ref('wh_dim_customers') }}
      where is_current = true
      group by customer_id
      having count(*) > 1

  - name: test_dim_product_scd_type2_integrity
    description: "Ensures SCD Type 2 integrity for product dimension"
    sql: |
      select product_id
      from {{ ref('wh_dim_products') }}
      where is_current = true
      group by product_id
      having count(*) > 1

  - name: test_fact_order_referential_integrity
    description: "Validates all order facts have valid dimensional references"
    sql: |
      select count(*)
      from {{ ref('wh_fact_orders') }} o
      left join {{ ref('wh_dim_customers') }} c on o.customer_key = c.customer_key
      left join {{ ref('wh_dim_date') }} d on o.order_date_key = d.date_key
      where c.customer_key is null or d.date_key is null

  - name: test_customer_journey_attribution_weights
    description: "Validates attribution weights sum correctly per order"
    sql: |
      select shopify_order_id
      from {{ ref('wh_fact_customer_journey') }}
      group by shopify_order_id
      having abs(sum(normalized_attribution_weight) - 1.0) > 0.01