version: 2

models:
  - name: stg_shopify_ecommerce__orders
    description: "Standardized Shopify orders from the Shopify package, including customer and financial information"
    columns:
      - name: order_id
        description: "Unique identifier for the order"
        data_tests:
          - unique
          - not_null
      - name: customer_id
        description: "Unique identifier for the customer"
      - name: order_total_price
        description: "Total price of the order including tax and shipping"
      - name: order_created_at
        description: "Timestamp when the order was created"

  - name: stg_shopify_ecommerce__customers
    description: "Standardized Shopify customer data with lifetime value metrics"
    columns:
      - name: customer_id
        description: "Unique identifier for the customer"
        data_tests:
          - unique
          - not_null
      - name: customer_email
        description: "Customer email address"
      - name: customer_lifetime_value
        description: "Total lifetime value of the customer"
      - name: customer_order_count
        description: "Total number of orders placed by the customer"

  - name: stg_shopify_ecommerce__order_lines
    description: "Standardized Shopify order line items with product details"
    columns:
      - name: order_line_id
        description: "Unique identifier for the order line"
        data_tests:
          - unique
          - not_null
      - name: order_id
        description: "Unique identifier for the parent order"
        data_tests:
          - not_null
      - name: product_id
        description: "Unique identifier for the product"
      - name: quantity
        description: "Quantity of the product ordered"
      - name: line_price
        description: "Total price for this line item"

  - name: stg_shopify_ecommerce__products
    description: "Standardized Shopify product catalog with sales metrics"
    columns:
      - name: product_id
        description: "Unique identifier for the product"
        data_tests:
          - unique
          - not_null
      - name: product_title
        description: "Product name/title"
      - name: product_vendor
        description: "Product vendor/brand"
      - name: total_sales
        description: "Total sales amount for this product"

  - name: stg_shopify_ecommerce__discounts
    description: "Standardized Shopify discount codes and their usage metrics"
    columns:
      - name: discount_code_id
        description: "Unique identifier for the discount code"
        data_tests:
          - unique
          - not_null
      - name: discount_code
        description: "The actual discount code used"
      - name: discount_value
        description: "Value of the discount"
      - name: total_discounted_orders
        description: "Total number of orders that used this discount"

  - name: stg_shopify_ecommerce__transactions
    description: "Standardized Shopify payment transactions"
    columns:
      - name: transaction_id
        description: "Unique identifier for the transaction"
        data_tests:
          - unique
          - not_null
      - name: order_id
        description: "Unique identifier for the related order"
      - name: transaction_amount
        description: "Transaction amount"
      - name: transaction_status
        description: "Status of the transaction (success, pending, error, etc.)"

  - name: stg_shopify_ecommerce__inventory_levels
    description: "Standardized Shopify inventory levels across locations"
    columns:
      - name: inventory_item_id
        description: "Unique identifier for the inventory item"
        data_tests:
          - not_null
      - name: location_id
        description: "Unique identifier for the location"
        data_tests:
          - not_null
      - name: inventory_available
        description: "Available inventory quantity"
      - name: variant_id
        description: "Product variant identifier"

  - name: stg_shopify_ecommerce__customer_cohorts
    description: "Standardized customer cohort analysis data"
    columns:
      - name: customer_id
        description: "Unique identifier for the customer"
        data_tests:
          - not_null
      - name: cohort_month
        description: "Month when customer first ordered"
      - name: period_number
        description: "Period number since first order"
      - name: order_seq_customer
        description: "Sequential order number for this customer"

  - name: stg_shopify_ecommerce__daily_shop
    description: "Standardized daily shop performance metrics"
    columns:
      - name: date_day
        description: "Date of the metrics"
        data_tests:
          - unique
          - not_null
      - name: orders_placed
        description: "Number of orders placed on this day"
      - name: gross_sales
        description: "Gross sales amount for the day"
      - name: net_sales
        description: "Net sales amount after refunds and discounts"