version: 2

models:
  - name: int_customers
    description: "Integration layer for customer data with calculated metrics and segmentation"
    columns:
      - name: customer_id
        description: "Unique identifier for customers from Shopify"
        tests:
          - unique
          - not_null
      - name: customer_email
        description: "Customer email address"
        tests:
          - not_null
      - name: calculated_lifetime_value
        description: "Calculated customer lifetime value based on actual orders"
        tests:
          - not_null
      - name: calculated_order_count
        description: "Count of orders for this customer"
        tests:
          - not_null
      - name: customer_segment
        description: "Customer segmentation based on order behavior"
        tests:
          - accepted_values:
              values: ['High Value', 'Repeat Customer', 'One-time Customer', 'No Orders']

  - name: int_orders
    description: "Integration layer for order data with line item aggregations and business metrics"
    columns:
      - name: order_id
        description: "Unique identifier for orders from Shopify"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Customer who placed the order"
        tests:
          - not_null
          - relationships:
              to: ref('int_customers')
              field: customer_id
      - name: order_total_price
        description: "Total price of the order"
        tests:
          - not_null
      - name: line_item_count
        description: "Number of line items in the order"
        tests:
          - not_null

  - name: int_products
    description: "Integration layer for product data with performance and inventory metrics"
    columns:
      - name: product_id
        description: "Unique identifier for products from Shopify"
        tests:
          - unique
          - not_null
      - name: product_title
        description: "Product title"
        tests:
          - not_null
      - name: total_revenue
        description: "Total revenue generated by this product"
        tests:
          - not_null
      - name: product_performance_category
        description: "Performance categorization based on sales"
        tests:
          - accepted_values:
              values: ['Best Seller', 'Popular', 'Moderate', 'Low Selling', 'No Sales']

  - name: int_sessions
    description: "Integration layer for website sessions with engagement and conversion metrics"
    columns:
      - name: session_id
        description: "Unique identifier for website sessions"
        tests:
          - unique
          - not_null
      - name: user_pseudo_id
        description: "User pseudo ID from website analytics"
        tests:
          - not_null
      - name: session_date
        description: "Date of the session"
        tests:
          - not_null
      - name: page_views
        description: "Number of page views in the session"
        tests:
          - not_null
      - name: session_type
        description: "Classification of session based on behavior"
        tests:
          - accepted_values:
              values: ['Converting', 'Checkout Started', 'Added to Cart', 'Product Browsing', 'General Browsing']

  - name: int_customer_journey
    description: "Integration layer linking website sessions to ecommerce conversions for customer journey analysis"
    columns:
      - name: shopify_customer_id
        description: "Ecommerce customer ID for the conversion"
        tests:
          - not_null
          - relationships:
              to: ref('int_customers')
              field: customer_id
      - name: shopify_order_id
        description: "Ecommerce order ID for the conversion"
        tests:
          - not_null
          - relationships:
              to: ref('int_orders')
              field: order_id
      - name: session_id
        description: "Website session ID"
        tests:
          - not_null
      - name: converting_user_pseudo_id
        description: "User pseudo ID for the converting user"
        tests:
          - not_null
      - name: journey_complexity
        description: "Classification of customer journey complexity"
        tests:
          - accepted_values:
              values: ['Single Session', 'Short Journey', 'Medium Journey', 'Long Journey']
      - name: conversion_timeline
        description: "Timeline from first touch to conversion"
        tests:
          - accepted_values:
              values: ['Same Day', 'Within 3 Days', 'Within 1 Week', 'Within 1 Month', 'Long Consideration']

tests:
  - name: test_customer_journey_order_mapping
    description: "Ensures customer journey records have valid order references"
    sql: |
      select shopify_order_id
      from {{ ref('int_customer_journey') }}
      where shopify_order_id not in (
        select order_id from {{ ref('int_orders') }}
      )

  - name: test_customer_journey_conversion_logic
    description: "Validates that converting sessions have purchase events"
    sql: |
      select session_id
      from {{ ref('int_customer_journey') }}
      where is_converting_session = true
        and session_type != 'Converting'