version: 2

models:
  - name: stg_ga4_events__page_view
    description: "GA4 page view events with extracted page parameters"
    columns:
      - name: event_id
        description: "Unique identifier for the event"
        data_tests:
          - unique
          - not_null
      - name: event_timestamp
        description: "Timestamp when the event occurred"
        data_tests:
          - not_null
      - name: user_pseudo_id
        description: "GA4 pseudo user identifier"
        data_tests:
          - not_null
      - name: event_name
        description: "Type of event (page_view)"
      - name: page_location
        description: "URL of the page viewed"
      - name: page_title
        description: "Title of the page viewed"
      - name: page_referrer
        description: "Referrer URL for the page view"

  - name: stg_ga4_events__session_start
    description: "GA4 session start events with session parameters"
    columns:
      - name: event_id
        description: "Unique identifier for the event"
        data_tests:
          - unique
          - not_null
      - name: event_timestamp
        description: "Timestamp when the session started"
        data_tests:
          - not_null
      - name: user_pseudo_id
        description: "GA4 pseudo user identifier"
        data_tests:
          - not_null
      - name: ga_session_id
        description: "GA4 session identifier"
      - name: ga_session_number
        description: "Sequential session number for the user"

  - name: stg_ga4_events__view_item
    description: "GA4 view item events with product details"
    columns:
      - name: event_id
        description: "Unique identifier for the event"
        data_tests:
          - unique
          - not_null
      - name: event_timestamp
        description: "Timestamp when the item was viewed"
        data_tests:
          - not_null
      - name: user_pseudo_id
        description: "GA4 pseudo user identifier"
        data_tests:
          - not_null
      - name: item_id
        description: "Product ID that was viewed"
      - name: item_name
        description: "Product name that was viewed"
      - name: item_category
        description: "Product category"
      - name: item_brand
        description: "Product brand"
      - name: item_price
        description: "Product price"
      - name: currency
        description: "Currency of the transaction"
      - name: value
        description: "Event value in the transaction currency"

  - name: stg_ga4_events__add_to_cart
    description: "GA4 add to cart events with product details"
    columns:
      - name: event_id
        description: "Unique identifier for the event"
        data_tests:
          - unique
          - not_null
      - name: event_timestamp
        description: "Timestamp when item was added to cart"
        data_tests:
          - not_null
      - name: user_pseudo_id
        description: "GA4 pseudo user identifier"
        data_tests:
          - not_null
      - name: item_id
        description: "Product ID added to cart"
      - name: item_name
        description: "Product name added to cart"
      - name: item_category
        description: "Product category"
      - name: item_brand
        description: "Product brand"
      - name: item_price
        description: "Product price"
      - name: item_quantity
        description: "Quantity added to cart"
      - name: currency
        description: "Currency of the transaction"
      - name: value
        description: "Total value of items added to cart"

  - name: stg_ga4_events__add_to_cart_items
    description: "Individual items from GA4 add to cart events (unnested)"
    columns:
      - name: item_event_id
        description: "Unique identifier for the item event"
        data_tests:
          - unique
          - not_null
      - name: parent_event_id
        description: "Reference to the parent add_to_cart event"
        data_tests:
          - not_null
      - name: event_timestamp
        description: "Timestamp when item was added to cart"
        data_tests:
          - not_null
      - name: user_pseudo_id
        description: "GA4 pseudo user identifier"
        data_tests:
          - not_null
      - name: item_sequence
        description: "Sequence number of item within the event"
      - name: item_id
        description: "Product ID"
      - name: item_name
        description: "Product name"
      - name: item_category
        description: "Product category"
      - name: item_brand
        description: "Product brand"
      - name: price
        description: "Unit price of the product"
      - name: quantity
        description: "Quantity of the product"
      - name: total_item_value
        description: "Total value (price * quantity)"

  - name: stg_ga4_events__begin_checkout
    description: "GA4 begin checkout events"
    columns:
      - name: event_id
        description: "Unique identifier for the event"
        data_tests:
          - unique
          - not_null
      - name: event_timestamp
        description: "Timestamp when checkout began"
        data_tests:
          - not_null
      - name: user_pseudo_id
        description: "GA4 pseudo user identifier"
        data_tests:
          - not_null
      - name: currency
        description: "Currency of the transaction"
      - name: value
        description: "Total checkout value"
      - name: item_count
        description: "Number of items in checkout"

  - name: stg_ga4_events__purchase
    description: "GA4 purchase events with transaction details"
    columns:
      - name: event_id
        description: "Unique identifier for the event"
        data_tests:
          - unique
          - not_null
      - name: event_timestamp
        description: "Timestamp when purchase occurred"
        data_tests:
          - not_null
      - name: user_pseudo_id
        description: "GA4 pseudo user identifier"
        data_tests:
          - not_null
      - name: transaction_id
        description: "Unique transaction identifier"
      - name: currency
        description: "Currency of the purchase"
      - name: value
        description: "Total purchase value"
      - name: item_count
        description: "Number of items purchased"

  - name: stg_ga4_events__add_payment_info
    description: "GA4 add payment info events"
    columns:
      - name: event_id
        description: "Unique identifier for the event"
        data_tests:
          - unique
          - not_null
      - name: event_timestamp
        description: "Timestamp when payment info was added"
        data_tests:
          - not_null
      - name: user_pseudo_id
        description: "GA4 pseudo user identifier"
        data_tests:
          - not_null
      - name: currency
        description: "Currency of the transaction"
      - name: value
        description: "Transaction value"
      - name: payment_type
        description: "Type of payment method"
      - name: item_count
        description: "Number of items in transaction"

  - name: stg_ga4_events__add_shipping_info
    description: "GA4 add shipping info events"
    columns:
      - name: event_id
        description: "Unique identifier for the event"
        data_tests:
          - unique
          - not_null
      - name: event_timestamp
        description: "Timestamp when shipping info was added"
        data_tests:
          - not_null
      - name: user_pseudo_id
        description: "GA4 pseudo user identifier"
        data_tests:
          - not_null
      - name: currency
        description: "Currency of the transaction"
      - name: value
        description: "Transaction value"
      - name: shipping_tier
        description: "Selected shipping tier/method"
      - name: item_count
        description: "Number of items for shipping"

# Referential integrity tests
tests:
  - name: test_add_to_cart_items_referential_integrity
    description: "Ensures all add_to_cart_items have valid parent events"
    sql: |
      select parent_event_id
      from {{ ref('stg_ga4_events__add_to_cart_items') }}
      where parent_event_id not in (
        select event_id from {{ ref('stg_ga4_events__add_to_cart') }}
      )